// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiContent.UI.WinUI;

#nullable disable

namespace TiContent.UI.WinUI.Migrations
{
    [DbContext(typeof(App.AppDataBaseContext))]
    [Migration("20250613181959_HydraFiltersV2")]
    partial class HydraFiltersV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("TiContent.Foundation.Entities.DB.DataBaseHistoryEntity", b =>
                {
                    b.Property<string>("Query")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Query");

                    b.ToTable("QueryHistoryItems");
                });

            modelBuilder.Entity("TiContent.Foundation.Entities.DB.DataBaseHydraFilterItemEntity", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilterType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Title");

                    b.ToTable("HydraFiltersItems");
                });

            modelBuilder.Entity("TiContent.Foundation.Entities.DB.DataBaseHydraLinkItemEntity", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("CleanTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FileSize")
                        .HasColumnType("REAL");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Title");

                    b.ToTable("HydraLinksItems");
                });

            modelBuilder.Entity("TiContent.Foundation.Entities.DB.DataBaseImageEntity", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Url");

                    b.ToTable("ImageItems");
                });
#pragma warning restore 612, 618
        }
    }
}
