//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiContent.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiContent.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate Jacred &amp; Hydra &amp; Hydra Links.
        /// </summary>
        public static string AboutPage_AppDescription {
            get {
                return ResourceManager.GetString("AboutPage.AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiContent by the_timick.
        /// </summary>
        public static string AboutPage_AppTitle {
            get {
                return ResourceManager.GetString("AboutPage.AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string AboutPage_Licences {
            get {
                return ResourceManager.GetString("AboutPage.Licences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPage_Title {
            get {
                return ResourceManager.GetString("AboutPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films &amp; Serials.
        /// </summary>
        public static string FilmsPage_Title {
            get {
                return ResourceManager.GetString("FilmsPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string GamesPage_Title {
            get {
                return ResourceManager.GetString("GamesPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty....
        /// </summary>
        public static string HomePage_Empty {
            get {
                return ResourceManager.GetString("HomePage.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please,wait....
        /// </summary>
        public static string HomePage_InProgress {
            get {
                return ResourceManager.GetString("HomePage.InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue.
        /// </summary>
        public static string MainWindow_NavigationItemHeader {
            get {
                return ResourceManager.GetString("MainWindow.NavigationItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiContent.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window position will be the same as last time on each startup.
        /// </summary>
        public static string SettingsPage_IsWindowOnCenterScreen_Description {
            get {
                return ResourceManager.GetString("SettingsPage.IsWindowOnCenterScreen.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember window position.
        /// </summary>
        public static string SettingsPage_IsWindowOnCenterScreen_Title {
            get {
                return ResourceManager.GetString("SettingsPage.IsWindowOnCenterScreen.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window size will be the same as last time on each startup.
        /// </summary>
        public static string SettingsPage_IsWindowSizePersistent_Description {
            get {
                return ResourceManager.GetString("SettingsPage.IsWindowSizePersistent.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember window size.
        /// </summary>
        public static string SettingsPage_IsWindowSizePersistent_Title {
            get {
                return ResourceManager.GetString("SettingsPage.IsWindowSizePersistent.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPage_Personalization {
            get {
                return ResourceManager.GetString("SettingsPage.Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the appearance theme.
        /// </summary>
        public static string SettingsPage_Theme_Description {
            get {
                return ResourceManager.GetString("SettingsPage.Theme.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPage_Theme_Item_0 {
            get {
                return ResourceManager.GetString("SettingsPage.Theme.Item.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPage_Theme_Item_1 {
            get {
                return ResourceManager.GetString("SettingsPage.Theme.Item.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows (default).
        /// </summary>
        public static string SettingsPage_Theme_Item_2 {
            get {
                return ResourceManager.GetString("SettingsPage.Theme.Item.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsPage_Theme_Title {
            get {
                return ResourceManager.GetString("SettingsPage.Theme.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage.Title", resourceCulture);
            }
        }
    }
}
